#!/bin/bash

access_token=$(az account get-access-token --resource https://storage.azure.com/ --query accessToken -o tsv)

json_output=$(cat <<EOF
{
  "headers": {
    "Authorization": ["Bearer $access_token"]
  }
}
EOF
)

echo "$json_output"
